sudo: required
services: 
  - docker

before_install: 
  - docker build -t mlsp/docker_react_travisci_aws -f Dockerfile.dev .

script:
  - docker run -e CI=true mlsp/docker_react_travisci_aws npm run test